apiVersion: v1
kind: Pod
metadata:
  name: web-ssh-${name.suffix}
  namespace: ${namespace}
  labels:
    app: web-ssh
  annotations:
    iam.host: ${iam.host}
spec:
  #serviceAccountName: zcp-system:zcp-system-sa-cloudzcp-admin
  #automountServiceAccountToken: false
  #securityContext:
  #  runAsUser: 1000
  restartPolicy: OnFailure
  containers:
  - name: alpine
    image: ${image}
    imagePullPolicy: Always
    env:
    - name: KUBE_TOKEN
      value: ${token}
    - name: NAMESPACE
      value: ${var_namespace}
    - name: USERNAME
      value: ${name.suffix}
    securityContext:
      #runAsUser: 0  #root
      allowPrivilegeEscalation: false