apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zcp-gitea
  namespace: zcp-system
  annotations:
    volume.beta.kubernetes.io/storage-class: pvretain
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: pvretain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zcp-gitea-postgres
  namespace: zcp-system
  annotations:
    volume.beta.kubernetes.io/storage-class: pvretain
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: pvretain
