apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zcp-jenkins
  namespace: zcp-system
  annotations:
    volume.beta.kubernetes.io/storage-class: ibmc-block-retain-silver
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ibmc-block-retain-silver
