apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: ibmc-file-retain-silver
  labels:
    billingType: "hourly"
    app: zcp-registry
    component: adminserver
    release: zcp-registry
  name: adminserver-config-zcp-registry-harbor-adminserver-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
