apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    #volume.beta.kubernetes.io/storage-class: ibmc-file-bronze
    volume.beta.kubernetes.io/storage-class: ibmc-block-retain-silver
  labels:
    billingType: "hourly"
    app: zcp-registry
    component: mysql
    release: zcp-registry
  name: mysql-data-zcp-registry-harbor-mysql-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
