apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    #volume.beta.kubernetes.io/storage-class: ibmc-file-bronze
    volume.beta.kubernetes.io/storage-class: ibmc-block-retain-silver
  labels:
    billingType: "hourly"
    app: zcp-registry-postgresql
    chart: postgresql-0.9.1
    heritage: Tiller
    release: zcp-registry
  name: zcp-registry-postgresql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
