image: "registry.au-syd.bluemix.net/cloudzcp/postgres"
imageTag: "9.6.2"

tolerations:
  - effect: NoSchedule
    key: management
    operator: Equal
    value: "true"
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: beta.kubernetes.io/arch
          operator: In
          values:
          - amd64
        - key: role
          operator: In
          values:
          - management

metrics:
  image: registry.au-syd.bluemix.net/cloudzcp/postgres_exporter

