apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: oidc-backup
    component: backup
  name: zcp-oidc-postgresql-backup
#  namespace: zcp-system
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                    - amd64
                  - key: role
                    operator: In
                    values:
                    - management
          initContainers:
          - args:
            - -c
            - /backup/scripts/dump-database.sh
            command:
            - /bin/sh
            image: registry.au-syd.bluemix.net/cloudzcp/k8s-kubectl:v1.9.7
            imagePullPolicy: IfNotPresent
            name: kubectl
            ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
            volumeMounts:
            - mountPath: /backup
              name: backup-dir
            - mountPath: /backup/scripts
              name: backup-scripts-config
          containers:
          - args:
            - -c
            - /backup/scripts/upload-to-s3.sh
            command:
            - /bin/sh
            image: registry.au-syd.bluemix.net/cloudzcp/aws-cli:1.14.5
            imagePullPolicy: IfNotPresent
            name: s3
            ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
            volumeMounts:
            - mountPath: /backup
              name: backup-dir
            - mountPath: /backup/scripts
              name: backup-scripts-config
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 0
          serviceAccount: zcp-system-admin
          serviceAccountName: zcp-system-admin
          tolerations:
          - effect: NoSchedule
            key: management
            operator: Equal
            value: "true"
          volumes:
          - emptyDir: {}
            name: backup-dir
          - configMap:
              defaultMode: 493
              name: zcp-oidc-postgresql-backup
            name: backup-scripts-config
  schedule: '5 16 * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
